name: Daily JPY-VND Rate Update

on:
  # Cho phép chạy workflow này thủ công từ giao diện GitHub
  workflow_dispatch:
  
  # Lên lịch chạy tự động
  schedule:
    # Chạy vào lúc 17:00 UTC mỗi ngày, tương đương 00:00 (nửa đêm) giờ Việt Nam (UTC+7)
    - cron: '0 17 * * *'

jobs:
  # Tên của job
  update_rate:
    # Chạy trên một máy ảo Ubuntu phiên bản mới nhất
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository của bạn
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt môi trường Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Bước 3: Cài đặt các thư viện cần thiết từ tệp requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bước 4: Chạy script Python
      - name: Run update script
        # Cung cấp các biến môi trường từ GitHub Secrets cho script
        env:
          CASPIO_CLIENT_ID: ${{ secrets.CASPIO_CLIENT_ID }}
          CASPIO_CLIENT_SECRET: ${{ secrets.CASPIO_CLIENT_SECRET }}
          CASPIO_TOKEN_ENDPOINT_URL: ${{ secrets.CASPIO_TOKEN_ENDPOINT_URL }}
          CASPIO_TABLE_API_URL: ${{ secrets.CASPIO_TABLE_API_URL }}
        run: python main.py
